language: csharp
mono: none
dotnet: 3.1
os: linux
dist: xenial

jobs:
    include:
      - os: linux
        dist: xenial
      - os: osx
        dotnet : 3.1.201
      - os: windows
        dotnet: none
        install: choco install dotnetcore-sdk --version 3.1.201

script:
    - dotnet fsi test.fsx

cache:
    directories:
        - ~/.nuget/packages

branches:
  only:
  - master
  - develop
